export const AUTHENTICATE = "AUTHENTICATE";
export const GET_ALL_POSTS = "GET_ALL_POSTS"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const DELETE_POST = "DELETE_POST";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";